//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.15 at 04:20:01 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:emergency:cap:1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.natepaulus.nws.weather.cap;
