//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.14 at 10:08:58 AM CST 
//


package com.natepaulus.nws.weather;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alert" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="headline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="phenomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alert"
})
@XmlRootElement(name = "alerts")
public class Alerts {

    protected List<Alerts.Alert> alert;
    @XmlAttribute(name = "title")
    protected String title;

    /**
     * Gets the value of the alert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alerts.Alert }
     * 
     * 
     */
    public List<Alerts.Alert> getAlert() {
        if (alert == null) {
            alert = new ArrayList<Alerts.Alert>();
        }
        return this.alert;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="headline" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="coordinates" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="phenomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "headline",
        "description",
        "instructions",
        "coordinates",
        "phenomena"
    })
    public static class Alert {

        @XmlElement(required = true)
        protected String headline;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String instructions;
        @XmlElement(required = true)
        protected String coordinates;
        @XmlElement(required = true)
        protected String phenomena;

        /**
         * Gets the value of the headline property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeadline() {
            return headline;
        }

        /**
         * Sets the value of the headline property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeadline(String value) {
            this.headline = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the instructions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstructions() {
            return instructions;
        }

        /**
         * Sets the value of the instructions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstructions(String value) {
            this.instructions = value;
        }

        /**
         * Gets the value of the coordinates property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoordinates() {
            return coordinates;
        }

        /**
         * Sets the value of the coordinates property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoordinates(String value) {
            this.coordinates = value;
        }

        /**
         * Gets the value of the phenomena property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhenomena() {
            return phenomena;
        }

        /**
         * Sets the value of the phenomena property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhenomena(String value) {
            this.phenomena = value;
        }

    }

}
